version: '2'
services:
    alphaserver-cassandra:
        container_name: alphaserver-cassandra
        image: cassandra:2.2.7
        # volumes:
        #     - ~/volumes/jhipster/alphaserver/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    alphaserver-cassandra-node:
        image: cassandra:2.2.7
        links:
            - alphaserver-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
    alphaserver-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: alphaserver-cassandra-migration
        links:
            - alphaserver-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
